describe('remote.watch', function()
  local tmp_state
  before_each(function()
    package.loaded['remote.watch'] = nil
    tmp_state = vim.fn.tempname() .. '.json'
  end)
  after_each(function()
    vim.fn.delete(tmp_state)
  end)

  it('add + list returns the new pattern', function()
    local w = require('remote.watch')
    w._set_state_path_for_test(tmp_state)
    local id = w.add('h1', '/var/log/app.log', 'ERROR', { level = 'ERROR' })
    local rows = w.list('h1', '/var/log/app.log')
    assert.are.equal(1, #rows)
    assert.are.equal(id, rows[1].id)
    assert.are.equal('ERROR', rows[1].regex)
    assert.True(rows[1].active)
  end)

  it('scan matches only active + returns the pattern entry', function()
    local w = require('remote.watch')
    w._set_state_path_for_test(tmp_state)
    local id = w.add('h', '/p', 'panic')
    w.add('h', '/p', 'debug', { active = false })
    local hits = w.scan('h', '/p', 'kernel panic at 42')
    assert.are.equal(1, #hits)
    assert.are.equal(id, hits[1].id)
  end)

  it('oneshot: active flips false after first match', function()
    local w = require('remote.watch')
    w._set_state_path_for_test(tmp_state)
    local id = w.add('h', '/p', 'boom', { oneshot = true })
    assert.are.equal(1, #w.scan('h', '/p', 'boom!'))
    assert.are.equal(0, #w.scan('h', '/p', 'boom!'))
  end)

  it('remove deletes the entry', function()
    local w = require('remote.watch')
    w._set_state_path_for_test(tmp_state)
    local id = w.add('h', '/p', 'x')
    w.remove(id)
    assert.are.equal(0, #w.list('h', '/p'))
  end)

  it('persists across reload', function()
    local w = require('remote.watch')
    w._set_state_path_for_test(tmp_state)
    local id = w.add('h', '/p', 'e')
    package.loaded['remote.watch'] = nil
    local w2 = require('remote.watch')
    w2._set_state_path_for_test(tmp_state)
    local rows = w2.list('h', '/p')
    assert.are.equal(1, #rows)
    assert.are.equal(id, rows[1].id)
  end)
end)
